name: bench-ruff-avrea-cold
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: avrea-ubuntu-latest-4-vcpu
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release 
